<?php

/**
 * Created by PhpStorm.
 * User: Sihua
 * Date: 2016/11/29
 * Time: 13:49
 */
class Human{
    protected function sayHi(){
        echo "Hi,I am a human!";
    }
}
class Person extends Human
{
    private $name;
    private $age;
    private $gender;
    const VERSION=2;

    /**
     * Person constructor.
     * @param $name
     * @param $age
     * @param $gender
     */
    public function __construct($name, $age, $gender)
    {
        $this->name = $name;
        $this->age = $age;
        $this->gender = $gender;
    }
    function showVersion(){
        echo self::VERSION;
    }
    function sayHi()
    {
        parent::sayHi(); // TODO: Change the autogenerated stub
        echo "<br/>Hi,I am $this->name;I am $this->age old;I am $this->gender";
    }

    function __clone()
    {
        // TODO: Implement __clone() method.
        $this->name="I am $that->name s";
        $this->age=10;
        $this->gender="M";
    }
}
$p1=new Person("Matthew",27,"M");
if($p1 instanceof Human) {
    $p2 = clone $p1;
    $p2->sayHi();
}

function __autoload($className){
    include strtolower($className).".class.php";
}


